const nodemailer = require('nodemailer');

// For the hackathon demo, we use Ethereal Email (a fake SMTP service)
// It logs the URL of the generated email so we can show it to the judges!
const transporter = nodemailer.createTransport({
  host: 'smtp.ethereal.email',
  port: 587,
  auth: {
    user: 'demarco.schneider@ethereal.email',
    pass: '1S7K8hK1W6Hj47Fp9w'
  }
});

const sendPurchaseOrderEmail = async (po) => {
  try {
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #0d8abc; color: white; padding: 20px; text-align: center;">
          <h1 style="margin: 0; font-size: 24px;">Shiv Furniture Works</h1>
          <p style="margin: 5px 0 0 0; opacity: 0.9;">Purchase Order</p>
        </div>
        
        <div style="padding: 30px;">
          <h2 style="color: #1e293b; margin-top: 0;">Hello ${po.vendor},</h2>
          <p style="color: #475569; line-height: 1.6;">
            Please find the details for our new Purchase Order <strong>${po.orderNo}</strong> below.
          </p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f8fafc; text-align: left;">
                <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Item</th>
                <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Quantity</th>
                <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Total</th>
              </tr>
            </thead>
            <tbody>
              ${po.items.map(item => `
                <tr>
                  <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; color: #334155;">${item.product?.name || 'Raw Material'}</td>
                  <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; color: #334155;">${item.qty}</td>
                  <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; color: #334155;">₹${item.totalPrice.toLocaleString('en-IN')}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          
          <div style="margin-top: 20px; text-align: right; font-size: 18px; font-weight: bold; color: #1e293b;">
            Total Amount: ₹${po.totalAmount.toLocaleString('en-IN')}
          </div>
        </div>
        
        <div style="background-color: #f8fafc; padding: 20px; text-align: center; color: #64748b; font-size: 12px;">
          This is an automated procurement email generated by ShivERP.
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: '"Shiv Procurement" <procurement@shiverp.demo>',
      to: po.vendorEmail || 'vendor@example.com',
      subject: `New Purchase Order: ${po.orderNo}`,
      html: htmlContent,
    });

    console.log(`[EMAIL SENT] PO ${po.orderNo} to ${po.vendor}`);
    console.log(`[EMAIL URL] Preview: ${nodemailer.getTestMessageUrl(info)}`);
    
    return { success: true, url: nodemailer.getTestMessageUrl(info) };
  } catch (error) {
    console.error('[EMAIL ERROR]', error);
    return { success: false, error: error.message };
  }
};

module.exports = {
  sendPurchaseOrderEmail
};
